services:
  app:
    build: .
    container_name: servicebox_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
      - storage:/var/www/html/storage
      - bootstrap_cache:/var/www/html/bootstrap/cache
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: servicebox
      DB_USERNAME: servicebox
      DB_PASSWORD: servicebox
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: servicebox_db
    environment:
      POSTGRES_DB: servicebox
      POSTGRES_USER: servicebox
      POSTGRES_PASSWORD: servicebox
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: nginx:alpine
    container_name: servicebox_web
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  pgdata:
  vendor:
  storage:
  bootstrap_cache:
